#
# 사이트 설정
#

# 테마 가져오기
theme: jekyll-theme-chirpy
# GitHub에 호스팅된 원격 테마를 지정합니다.
remote-theme: cotes2020/jekyll-theme-chirpy

# GitHub Pages 프로젝트 사이트(예: username.github.io/project-name)이고 사용자 정의 도메인이 없는 경우에만
# '/프로젝트_이름' 값으로 변경하세요.
baseurl: ""

# 웹페이지 언어 설정 › http://www.lingoes.net/en/translator/langcode.htm
# _data/locales 폴더에 있는 파일 중 하나와 이름이 같으면 레이아웃 언어도 변경됩니다.
# 그렇지 않으면 레이아웃 언어는 기본값인 'en'을 사용합니다.
lang: en

# 시간대 변경 › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Seoul

# jekyll-seo-tag 설정 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Hoya Blog # 메인 타이틀

tagline: 오늘의 고민이 내일의 성장이 되도록 # 태그라인

description: >- # SEO 메타 및 atom 피드에서 사용됩니다.
  안녕하세요. 개발자 Hoya의 기술 블로그입니다. 개발하며 얻은 경험과 인사이트, 그리고 성장을 위한 학습 노트를 기록하는 공간입니다.

# 사이트의 프로토콜과 호스트 이름을 입력하세요. 예: 'https://username.github.io'
url: "https://leehh312.github.io"

github:
  username: leehh312 # GitHub 사용자 이름으로 변경

twitter:
  username: twitter_username # 트위터 사용자 이름으로 변경

social:
  # 전체 이름으로 변경하세요.
  # 게시물의 기본 작성자 및 푸터의 저작권자로 표시됩니다.
  name: Hoya
  email: leehh312@gmail.com # 이메일 주소로 변경
  links:
    # 첫 번째 요소는 저작권자의 링크로 사용됩니다.
    # - https://twitter.com/username      # 트위터 홈페이지로 변경
    - https://github.com/leehh312 # GitHub 홈페이지로 변경
    # 더 많은 소셜 링크를 추가하려면 아래 주석을 해제하세요.
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: Zj0hq0s4_FY4rv4JFeJQKYam8CRotbDPLJnICHCcmJs # Google Search Console 인증 코드

# ↑ --------------------------
# `jekyll-seo-tag` 설정 끝

google_analytics:
  id: G-KWP7QP43NG # Google Analytics ID를 입력하세요.
  # Google Analytics 페이지뷰 리포트 설정
  pv:
    proxy_endpoint: # Google App Engine의 Google Analytics superProxy 엔드포인트를 입력하세요.
    cache_path: # 로컬 페이지뷰(PV) 캐시 데이터, 중국 방화벽(GFW) 지역 방문자에게 유용합니다.

# 선호하는 색상 스킴 설정.
#
# 참고: 비워두면 기본적으로 시스템 선호 색상을 따르며,
# 사이드바 하단 왼쪽에 다크/라이트 테마 전환 토글이 표시됩니다.
#
# 사용 가능한 옵션:
#
#     light  - 라이트 색상 스킴 사용
#     dark   - 다크 색상 스킴 사용
#
theme_mode: dark # [light|dark]

# 이미지용 CDN 엔드포인트.
# 참고: 할당되면 '/'로 시작하는 모든 이미지(사이트 아바타 및 게시물 이미지) 경로에
# CDN URL이 추가됩니다.
#
# 예: 'https://cdn.com'
img_cdn:

# 사이드바 아바타, 로컬 또는 CORS 리소스를 지원합니다.
avatar: "/assets/img/avatar.jpg"

# boolean 타입, 게시물 목차(ToC)의 전역 스위치입니다.
toc: true

comments:
  active: # 게시물 댓글의 전역 스위치입니다. 예: 'disqus'. 비워두면 비활성화됩니다.
  # 활성화 가능한 옵션은 다음과 같습니다:
  disqus:
    shortname: # Disqus shortname을 입력하세요. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 설정 › https://utteranc.es/
  utterances:
    repo: # <GitHub사용자명>/<저장소명>
    issue_term: # < url | pathname | title | ...>
  # Giscus 옵션 › https://giscus.app
  giscus:
    repo: # <GitHub사용자명>/<저장소명>
    repo_id: # Giscus 설정 시 발급받는 저장소 ID
    category: # 토론이 생성될 카테고리
    category_id: # 카테고리 ID
    mapping: # 선택 사항, 기본값 'pathname'
    input_position: # 선택 사항, 기본값 'bottom'
    lang: # 선택 사항, 기본값 `site.lang`
    reactions_enabled: # 선택 사항, 기본값 '1'

# 자체 호스팅 정적 자산, 선택 사항 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, 비워두면 false를 의미합니다.
    # Jekyll 환경 지정, 비워두면 모두 해당됩니다.
    # `assets.self_host.enabled`가 'true'일 경우에만 작동합니다.
    env: # [development|production]

pwa:
  enabled: true # PWA(Progressive Web App) 기능 활성화 옵션

paginate: 6 # 한 페이지에 보여줄 게시물 수

# ------------ 아래 옵션은 수정하지 않는 것을 권장합니다 ------------------

# 마크다운 렌더러(kramdown) 설정
kramdown:
  # 코드 블록 문법 강조(syntax highlighting)에 사용할 라이브러리
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 옵션 › https://github.com/jneen/rouge#full-options
    css_class: highlight # 코드 블록에 적용될 CSS 클래스
    # default_lang: console
    span:
      line_numbers: false # 인라인 코드에 줄 번호 표시 여부
    block:
      line_numbers: true # 코드 블록에 줄 번호 표시 여부
      start_line: 1 # 코드 블록 줄 번호 시작 숫자

# 컬렉션 설정 (상단 탭 메뉴 등을 정의)
collections:
  tabs:
    output: true # 컬렉션 내 문서들을 개별 파일로 생성할지 여부
    sort_by: order # 컬렉션 문서 정렬 기준 (front matter의 'order' 값)

# 특정 경로 및 타입에 대한 Front Matter 기본값 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /categories/:categories/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # `site.collections` 참조
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# SASS/SCSS 컴파일 스타일 (compressed: 압축하여 용량 최소화)
sass:
  style: compressed

# HTML 파일 압축 설정 (사이트 로딩 속도 향상)
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Jekyll 빌드 시 제외할 파일 및 폴더 목록
exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

# jekyll-archives 플러그인 설정 (카테고리 및 태그 페이지 자동 생성)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
